src/entities/Proposal/types.ts, src/pages/submit/grant.tsx
Proposal: [Expanding the Community Grants Program](https://governance.decentraland.org/proposal/?id=c02ff450-2783-11ec-ac84-77607720a240)
=> Include new grant tires

src/components/Proposal/Submit/ProposalSubmitPoiPage.tsx, src/intl/en.json, src/pages/submit/ban-name.tsx, src/pages/submit/catalyst.tsx, src/pages/submit/draft.tsx, src/pages/submit/governance.tsx, src/pages/submit/grant.tsx, src/pages/submit/poll.tsx
This PR addresses [this issue](https://github.com/decentraland/governance/issues/164)
All forms are now disabled when submitting.
=> 164 - Disable form while submitting

src/components/Modal/VoteListItem.tsx, src/components/Modal/VotesList.css, src/components/Modal/VotesList.tsx, src/components/Section/DetailsSection.css, src/entities/Proposal/templates/messages.ts, src/pages/proposal.tsx
This is how it looked
With the fix
=> Align labels

README.md, package-lock.json, package.json, src/components/Section/DetailItem.css, src/components/Token/TokenBalanceCard.tsx, src/components/Transparency/MonthlyTotal.css, src/components/Transparency/MonthlyTotal.tsx, src/pages/transparency.css, src/pages/transparency.tsx
=> Transparency weth logo

src/intl/en.json, src/pages/transparency.tsx
Header should display `Transparency` but mission section title should be `Our Mission` @yemel
=> Change mission section title

src/api/Snapshot.ts, src/components/Form/MarkdownNotice.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDistribution.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDistribution.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDistributionPopup.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDistributionPopup.tsx, src/components/Token/LandBalanceCard.tsx, src/components/Token/NameBalanceCard.tsx, src/components/Token/TokensPerWalletPopup.css, src/components/Transparency/MembersSection.css, src/components/Transparency/MembersSection.tsx, src/components/User/UserStats.tsx, src/entities/Proposal/types.ts, src/hooks/useAbbreviatedNumber.ts, src/hooks/useContract.ts, src/intl/en.json, src/theme.css
=> Add voting power stats to delegates detail modal

src/api/Snapshot.ts, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/hooks/useDelegation.ts, src/intl/en.json
Missing type of proposal and status. Figuring out best way to fetch all proposals from our db as this data is not in snapshot.
=> Show list of voted proposals in candidate detail

src/api/Governance.ts, src/api/Snapshot.ts, src/components/Modal/VotingPowerDelegationDetail/VotedInitiative.css, src/components/Modal/VotingPowerDelegationDetail/VotedInitiative.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/components/Modal/VotingPowerDelegationModal/VotingPowerDelegationModal.tsx, src/components/Status/StatusLabel.css, src/components/Status/StatusLabel.tsx, src/entities/Proposal/model.ts, src/entities/Votes/routes.ts, src/entities/Votes/types.ts
=> Add proposal status and type to initiatives list

src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDistributionPopup.tsx, src/intl/en.json
=> Add loader to delegation detail modal + style fixes

src/hooks/useDelegation.test.ts, src/hooks/useDelegation.ts
=> Fix: Delegations not displaying properly

src/components/Modal/VotingPowerDelegationDetail/CandidateMatch.css, src/components/Modal/VotingPowerDelegationDetail/VotedInitiative.css, src/components/Modal/VotingPowerDelegationDetail/VotedInitiative.tsx, src/components/Modal/VotingPowerDelegationDetail/VotedInitiativeList.css, src/components/Modal/VotingPowerDelegationDetail/VotedInitiativeList.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/entities/Snapshot/utils.ts, src/intl/en.json
* Added view more button
* Removed proposal type and status
=> Voted initiative list improvements

src/api/Snapshot.ts, src/components/Delegation/DelegatedToUserCard.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDistributionPopup.css, src/components/Section/ProposalResultSection.tsx, src/components/Section/ProposalVoting/ChoiceButtons.tsx, src/components/Section/ProposalVoting/ProposalVotingSection.css, src/components/Section/ProposalVoting/ProposalVotingSection.tsx, src/components/Section/ProposalVoting/VoteVotingPowerInfo.tsx, src/components/Section/ProposalVoting/VotingSectionFooter.tsx, src/components/Section/VotingSectionTester.css, src/components/Section/VotingSectionTester.tsx, src/entities/Proposal/jobs.ts, src/entities/Votes/routes.ts, src/entities/Votes/utils.ts, src/hooks/useVotingPowerBalance.ts, src/hooks/useVotingPowerBalanceList.ts, src/hooks/useVotingPowerInformation.ts, src/hooks/useVotingPowerOnProposal.ts, src/hooks/useVotingSectionTestData.ts, src/modules/votes/utils.ts, src/theme.css
Use VP at the proposal time of creation instead of the latest VP.
=> Voting with calculation

src/components/Delegation/DelegatedToUserCard.tsx
=> Fix: "Cannot read properties of undefined (ownVp)"

src/components/Delegation/DelegatedCardProfile.css, src/components/Delegation/DelegatedCardProfile.tsx, src/components/Delegation/VotingPowerListItem.css, src/components/Delegation/VotingPowerListItem.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/components/Modal/VotingPowerDelegationList/VotingPowerDelegationItem.tsx, src/components/Modal/VotingPowerDelegationModal/VotingPowerDelegationModal.css, src/components/User/UserStats.css, src/components/User/UserStats.tsx, src/components/User/Username.css, src/components/User/Username.tsx
Fixed Username display styles, and blockie vs avatar sizes w/ @ncomerci
=> Username fixes

.env.example, Pulumi.website-dao-dev.yml, Pulumi.website-dao-prd.yml, src/components/Section/VestingSection.css, src/components/Section/VestingSection.tsx, src/intl/en.json, src/pages/proposal.tsx
Vesting section on enacted grants.
Co-authored-by: heyimjuani <hey@juan-i.com.ar>
(cherry picked from commit e0576e68bf41b45fd105f086900e05d2a65d0596)
=> Release 06-02-2022

Pulumi.website-dao-dev.yml, Pulumi.website-dao-prd.yml
Revert env files to commit [#d2f3ecd](https://github.com/decentraland/governance/commit/d2f3ecdb30548d338382723fa98c90d6205aee03), adding new relic creds and vesting dashboard url
=> Env vars fix

package-lock.json, package.json
New update fixes Container/NavBar invalid className prop error.
=> chore: add and update decentraland-ui

.env.example
Remember to add it to .env.development to disable locally :)
=> Add env var to disable new relic locally

package-lock.json, package.json, src/entities/Proposal/templates/messages.test.ts, src/entities/Proposal/templates/messages.ts, tsconfig.json
- Added [lazy var init for testing](https://github.com/stalniy/bdd-lazy-var)
- Refactored proposal messages test
- Fix job triggered update message
=> Fix proposal update messages test

.eslintrc.json, src/components/Layout/TextLabel.css, src/components/Section/ProposalPromotionSection.tsx
=> fix: align proposal promotion label

src/pages/transparency.css
=> fix: transparency tokens odd number styles

src/components/Section/ProposalDetailSection.tsx, src/components/Status/FinishLabel.tsx
=> feat: add date tag in proposals dates

src/entities/Proposal/routes.ts
Closes https://github.com/decentraland/governance/issues/379
- Before
- After
=> Allow for 2 character search terms

src/components/Banner/Banner.css, src/components/Grants/FilterButton.css, src/components/Grants/FilterButton.tsx, src/components/Grants/PercentageLabel.css, src/components/Icon/Sort.tsx, src/components/Modal/VotingPowerDelegationList/VotingPowerDelegationList.tsx, src/components/Proposal/Update/ProposalUpdate.css, src/components/Section/ProposalVoting/ChoiceButton.css, src/components/Transparency/MonthlyTotal.css, src/components/Updates/ProjectHealthButton.css, src/components/Updates/ProjectHealthStatus.css, src/hooks/useSortingByKey.ts, src/intl/en.json, src/pages/grants.css, src/pages/grants.tsx, src/pages/submit/index.tsx, src/theme.css
=> feat: filter current grants by category + sort past grants by date

src/intl/en.json
=> Minor change in coauthoring labels and descriptions

src/api/Governance.ts, src/components/Modal/UpdateProposalStatusModal/UpdateProposalStatusModal.css, src/components/Modal/UpdateProposalStatusModal/UpdateProposalStatusModal.tsx, src/entities/Proposal/routes.ts, src/entities/Proposal/templates/messages.test.ts, src/entities/Proposal/templates/messages.ts, src/entities/Proposal/types.ts, src/entities/Proposal/utils.ts, src/intl/en.json, src/migrations/1656683905520_add-enacting-tx-to-proposals.ts, src/migrations/1656683997915_populate-enacting-tx.ts, src/pages/proposal.tsx
* Add enacting tx to proposals
* Add address length validation to schema
* Add more transaction hashes to enacted proposals
* Refactors addressing comments
Co-authored-by: 1emu <github@1emu.sh>
(cherry picked from commit 8e3d535ce6963e20772c0460d6c504b2d056a016)
=> Release 07-08-2022

src/migrations/1657566787280_add-corresponding-vesting-address-to-existing-proposals-2.ts
Found this two with an enacted description but without the vesting address
=> Fill proposals vesting address

src/components/Grants/CurrentGrantsSortingMenu.css, src/components/Grants/CurrentGrantsSortingMenu.tsx, src/components/Grants/GrantsPastItem.css, src/components/Grants/GrantsPastItem.tsx, src/components/Grants/PastGrantCard.css, src/components/Grants/PastGrantCard.tsx, src/components/Grants/PastGrantsBanner.tsx, src/components/Grants/PastGrantsList.css, src/components/Grants/PastGrantsList.tsx, src/components/Grants/PastGrantsTable.css, src/components/Grants/PastGrantsTable.tsx, src/components/Icon/Sort.tsx, src/hooks/useSortingByKey.ts, src/intl/en.json, src/pages/grants.css, src/theme.css
=> feat: past grants list for mobile.

src/pages/proposal.css, src/pages/proposal.tsx
=> feat: make proposal sidebar sticky

src/components/Common/Pill.css, src/components/Common/Pill.tsx, src/components/Status/StatusPill.tsx
=> feat: add pill style outline

src/components/Grants/VestingProgress.tsx
fix: vested/transferred amount in grants page (#423)
=> Release 07-20-2022 (Fix)

src/components/Grants/GrantCard.css, src/components/Grants/GrantCard.tsx
=> fix: Grant cards size in USD

src/entities/Proposal/routes.ts
"Keep polygon..." contract was enacted on polygon.
=> fix: filter grants with undefined address/tx

src/components/Common/DateTooltip.tsx, src/components/Grants/CliffNotice.css, src/components/Grants/CliffNotice.tsx, src/components/Grants/CliffProgress.css, src/components/Grants/CliffProgress.tsx, src/components/Grants/GrantCard.tsx, src/components/Icon/InfoCircle.tsx, src/components/Proposal/Update/CollapsedProposalUpdate.tsx, src/components/Proposal/Update/ExpandedProposalUpdate.tsx, src/components/Section/ProposalDetailSection.tsx, src/components/Section/ProposalVestingStatus.tsx, src/components/Status/FinishLabel.tsx, src/components/Updates/UpdateMarkdownView.tsx, src/entities/Proposal/types.ts, src/entities/Proposal/utils.ts, src/intl/en.json
=> Grant Cards Cliff Data

src/api/Governance.ts
=> fix: parse proposal dates on status update

src/intl/en.json
=> feat: update title and description tags in grants page

src/entities/Proposal/templates/index.ts
=> feat: update forum title format

src/api/DclData.ts, src/components/Helper/Helper.tsx, src/components/Section/DetailItem.css, src/components/Section/DetailItem.tsx, src/components/Transparency/MonthlyTotal.css, src/components/Transparency/MonthlyTotal.tsx, src/entities/Proposal/templates/index.ts, src/pages/proposal.tsx
* fix: show updates on enacted grants
* feat: use last 7 chars of snapshot id in discourse title
* feat: update discourse post title format
* transaction tags overview
=> Release 07-27-2022

src/components/Grants/CurrentGrantsList.tsx, src/components/Grants/CurrentGrantsSortingMenu.tsx, src/entities/Proposal/routes.ts, src/intl/en.json
=> feat: add last updated filter to current grants list

src/components/Home/OpenProposal.css, src/components/Home/OpenProposal.tsx, src/intl/en.json
=> Votes view in open proposals

src/components/Home/ActiveCommunityGrants.css, src/components/Home/ActiveCommunityGrants.tsx, src/components/Home/Charts.css, src/components/Home/Charts.tsx, src/components/Home/CommunityEngagement.tsx, src/components/Home/DaoDelegates.css, src/components/Home/DaoDelegates.tsx, src/components/Home/HomeLoader.css, src/components/Home/HomeLoader.tsx, src/components/Home/MetricsCard.css, src/components/Home/MetricsCard.tsx, src/components/Home/MetricsCards.tsx, src/components/Home/OpenProposals.css, src/components/Home/OpenProposals.tsx, src/components/Home/TopVoters.css, src/components/Home/TopVoters.tsx, src/components/Table/DelegatesTable.css, src/components/Table/DelegatesTable.tsx, src/hooks/useProposalsByParticipatingVP.ts, src/intl/en.json
=> feat: add home loading states

src/components/Grants/Banner.css, src/components/Grants/CurrentGrantsList.css, src/components/Home/ActiveCommunityGrants.css, src/components/Home/BottomBanner/Action.css, src/components/Home/BottomBanner/Action.tsx, src/components/Home/BottomBanner/BottomBanner.css, src/components/Home/BottomBanner/BottomBanner.tsx, src/components/Home/Charts.css, src/components/Home/CommunityEngagement.css, src/components/Home/CommunityEngagement.tsx, src/components/Home/OpenProposal.css, src/components/Home/TopVoters.css, src/components/Table/DelegatesTableRow.tsx, src/modules/time.test.ts, src/modules/time.ts
Before
After
- Abbreviate delegates displayed time differences
=> Community engagement display fix

src/components/Section/ProposalVoting/ChoiceButton.css, src/components/Status/ChoiceProgress.tsx
Before:
After:
Reproducible in https://governance.decentraland.org/proposal/?id=a85bae50-1f0d-11ed-9342-4f244be49f84
=> fix: choice progress color

src/components/Layout/BurgerMenu/BurgerMenuPushableLayout.tsx
https://user-images.githubusercontent.com/45410089/188507015-d6189f2e-8782-4e29-8f71-d42302596546.mov
=> fix: proposal list not showing properly

src/components/Profile/ProfileBox.css, src/components/Profile/ProfileBox.tsx
First version for this component, we can add things to it as we need.
=> feat: profile box component

src/entities/Proposal/types.ts
As reported by Tony on Discord.
=> fix: poi coords in submit validation

src/entities/Proposal/utils.ts, src/intl/en.json, src/pages/proposal.tsx
This PR enables the DAO Committee to edit proposal enactment data.
=> feat: Edit enactment data

src/migrations/1663608324933_add-coauthors-to-core-units-grants.ts
As requested by DAO Committee members, we are adding co-authors to already published proposals to optimize the Project Updates publication flow.
=> feat: add coauthors to previous core units grants

src/components/Proposal/Update/CollapsedProposalUpdate.tsx, src/components/Proposal/Update/ProposalUpdate.tsx, src/components/Proposal/Update/ProposalUpdates.tsx, src/entities/Proposal/utils.ts, src/entities/Updates/routes.ts, src/pages/proposal.tsx
* fix: some coauthor addresses not showing update button
* feat: show post update button to coauthors in updates list
=> Release 2022-09-26

src/clients/SnapshotGraphql.ts, src/clients/SnapshotSubgraph.ts, src/entities/Snapshot/queries.ts, src/entities/Snapshot/utils.ts, src/hooks/useDelegation.ts, src/hooks/useDelegationOnProposal.ts, src/hooks/usePickedBy.ts
Tested with user 0xd5e9ef1cedad0d135d543d286a2c190b16cbb89e.
Before:
After:
=> fix: snapshot delegations query limit 

src/components/Grants/GrantBeneficiaryItem.css
=> Grant beneficiary mobile

src/components/Delegation/DelegationCards.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationHandler.css, src/components/Profile/VpDelegationBox.css, src/components/Profile/VpDelegationBox.tsx, src/components/Profile/VpDelegatorsBox.tsx, src/intl/en.json, src/pages/profile.tsx
=> Delegated VP card & minor fixes

src/components/Grants/GrantBeneficiaryItem.tsx
=> fix: Grant tier symbol

src/clients/Governance.ts, src/components/Icon/DotsMenu.tsx, src/components/Modal/DeleteUpdateModal/DeleteUpdateModal.tsx, src/components/Proposal/Update/CollapsedProposalUpdate.tsx, src/components/Proposal/Update/ExpandedProposalUpdate.tsx, src/components/Proposal/Update/ProposalUpdate.css, src/components/Proposal/Update/ProposalUpdate.tsx, src/components/Proposal/Update/ProposalUpdates.tsx, src/components/Proposal/Update/UpdateMenu.css, src/components/Proposal/Update/UpdateMenu.tsx, src/entities/Updates/routes.ts, src/hooks/useProposalUpdates.ts, src/intl/en.json, src/pages/proposal.tsx, src/pages/update.css, src/pages/update.tsx
=> feat: delete update from updates list

src/clients/SnapshotGraphql.ts, src/clients/SnapshotGraphqlTypes.ts, src/entities/Proposal/jobs.ts, src/entities/Proposal/model.ts
Co-authored-by: andyesp <andyespagnolo@gmail.com>
=> chore: use proposal graphql endpoint to get scores

src/clients/Governance.ts, src/clients/SnapshotGraphql.ts, src/clients/SnapshotGraphqlTypes.ts, src/components/Profile/VotedProposalsBox.css, src/components/Profile/VotedProposalsBox.tsx, src/components/Profile/VpDelegatorsBox.css, src/components/Profile/VpDelegatorsBox.tsx, src/components/Proposal/ProfileProposalItem.css, src/components/Proposal/ProfileProposalItem.tsx, src/components/Proposal/ResultStance.css, src/components/Proposal/ResultStance.tsx, src/entities/Snapshot/outcomeMatch.test.ts, src/entities/Snapshot/outcomeMatchData.ts, src/entities/Votes/routes.ts, src/entities/Votes/types.ts, src/hooks/useVotedProposals.ts, src/hooks/useVotesMatch.ts, src/intl/en.json, src/pages/profile.tsx
=> feat: Voted proposals on profile

src/components/Proposal/ProposalComments.css, src/components/Proposal/ProposalComments.tsx, src/services/DiscourseService.ts
=> Forum comments fix

src/clients/DclData.ts, src/components/Grants/GrantBeneficiaryItem.tsx, src/components/Grants/GrantCard/ProgressBarTooltip.tsx, src/components/Grants/GrantCard/VestingProgress.tsx, src/entities/Proposal/routes.ts, src/entities/Proposal/types.ts
=> fix: Grant transparency data

src/components/Grants/GrantBeneficiaryItem.css, src/components/Grants/GrantBeneficiaryItem.tsx, src/components/Icon/ChevronRightCircleOutline.css, src/components/Icon/ChevronRightCircleOutline.tsx, src/components/Profile/ProposalCreatedItem.css, src/components/Profile/ProposalCreatedItem.tsx, src/components/Proposal/ProfileProposalItem.css, src/components/Proposal/ProfileProposalItem.tsx, src/intl/en.json
=> fix: profile alignment styles

src/components/Proposal/ProfileProposalItem.css, src/components/Proposal/ProfileProposalItem.tsx
=> fix: style in voted proposal category pill

src/components/Home/CommunityEngagement.tsx, src/components/Home/DaoDelegates.tsx, src/components/Home/MetricsCard.tsx, src/components/Home/MetricsCards.tsx, src/pages/index.css, src/pages/index.tsx
=> feat: kpi cards clickable

src/clients/SnapshotGraphql.ts, src/clients/utils.ts
Co-authored-by: ncomerci <nicolas.comerci@decentraland.org>
=> fix: snapshot queries in home page

src/pages/proposal.css
=> styles: improve proposal subtitles contrast

src/components/Home/MainBanner.css, src/components/Home/MainBanner.tsx, src/components/Icon/CloseCircle.tsx, src/intl/en.json, src/pages/index.tsx
=> feat: dismiss home banner

src/components/Proposal/ProposalComment.css
=> fix: images in mobile proposal comments

src/migrations/1663608324933_add-coauthors-to-core-units-grants.ts
This reverts commit a594597cf0c49b7e19040b7f5825be78f0a8ed54.
=> Revert "chore: remove proposal coauthors update migration (#671)"

src/components/Updates/UpdateMarkdownView.tsx, src/intl/en.json, src/pages/update.tsx
=> fix: update detail page issues

src/components/Proposal/ProposalComment.css, src/components/Proposal/ProposalComment.tsx, src/components/Proposal/ProposalComments.tsx, src/entities/Discourse/utils.ts
Closes #545 and #544
feat: avatar and username link to discourse user url in proposal comments
fix: discourse user mentions
=> feat: discourse comments user links improvements

src/intl/en.json
=> feat: add category budget copy

src/components/Grants/CategorySelector.css, src/components/Grants/CategorySelector.tsx, src/intl/en.json
=> feat: add category selector texts

src/entities/Proposal/utils.ts, src/services/ProposalService.ts
Review after merging #699 
Remove validation blocking the grants creation
=> Re-enable grant creation

src/components/Home/MetricsCard.css, src/components/Home/MetricsCard.tsx, src/components/Home/MetricsCards.css, src/components/Home/MetricsCards.tsx
=> refactor: remove flickity from home metrics cards

src/constants.ts
Signed-off-by: Gino Cingolani <gino@decentraland.org>
=> chore: updating Discord invite link

src/components/Category/CategoryList.tsx, src/components/Category/CategoryOption.css, src/components/Category/CategoryOption.tsx, src/components/Grants/Current/CurrentGrantsBanner.tsx, src/components/Grants/Current/CurrentGrantsList.css, src/components/Grants/Current/CurrentGrantsList.tsx, src/components/Layout/BurgerMenu/BurgerMenuContent.tsx, src/components/Search/CategoryFilter.tsx, src/entities/Proposal/routes.ts, src/entities/Proposal/types.ts, src/intl/en.json, src/pages/grants.tsx
=> Category counter, empty & mobile view

.env.example, src/clients/Decentraland.ts, src/config/env/dev.json, src/config/env/heroku.json, src/config/env/local.json, src/config/env/prd.json
Using a new lambda for mail subscription
=> feat: change subscribe endpoint

src/components/GrantRequest/CalculationHelper.tsx, src/components/GrantRequest/GrantRequestFundingSection.tsx, src/intl/en.json
=> feat: add helper to lock icon in calculation boxes

src/components/Grants/Current/BudgetBanner.tsx, src/hooks/useBudgetByCategory.ts
Use ceiling of consumed percentage for grants banner display
=> Grants banner minor refactor

src/components/Category/CategoryPill.tsx, src/components/Common/DateTooltip.tsx, src/components/Home/OpenProposal.tsx, src/components/Profile/ProposalCreatedItem.tsx, src/components/Proposal/ProfileProposalItem.tsx, src/components/Proposal/ProposalCard.tsx, src/components/Proposal/ProposalItem.css, src/components/Proposal/ProposalItem.tsx, src/components/Status/FinishLabel.css, src/components/Status/FinishLabel.tsx, src/components/Status/StatusPill.tsx, src/entities/Proposal/templates/messages.ts, src/entities/Proposal/utils.ts, src/pages/proposal.tsx
=> Pill names and sizes

src/components/GrantRequest/CategorySection/DocumentationSection.tsx, src/components/GrantRequest/CategorySection/SponsorshipSection.tsx, src/components/GrantRequest/GrantRequestFinalConsentSection.tsx, src/constants.ts, src/intl/en.json
~~On hold until license link and its final text is defined~~
=> feat: Platform final consent split

src/intl/en.json, src/pages/submit/grant.tsx
=> feat: Grant template link

src/entities/Proposal/templates/grant.ts
=> feat: Size in grants header

src/entities/Proposal/templates/grant.ts
=> feat: rename specification in description

src/clients/utils.ts, src/components/Category/CategoryList.tsx, src/components/Search/CategoryFilter.tsx, src/components/Search/SortingMenu.tsx, src/components/Search/StatusFilter.tsx, src/entities/Budget/routes.ts, src/entities/Budget/types.ts, src/entities/Proposal/model.ts, src/entities/Proposal/testHelpers.ts, src/helpers/index.ts, src/services/BudgetService.test.ts, src/services/BudgetService.ts, src/services/DiscordService.ts, src/services/ProposalService.test.ts, src/services/ProposalService.ts
Created `api/budget/expected` endpoint that returns this object
```json
{
"id": "a4d59550-b79e-11ed-b818-c9745d1220a5",
"start_at": "2023-01-01T00:00:00.000Z",
"finish_at": "2023-04-01T00:00:00.000Z",
"total": 1155000,
"allocated": 0,
"categories": {
"accelerator": {
"total": 80850,
"allocated": 0,
"available": 80850,
"contested": 25500,
"contested_over_available_percentage": 32,
"contestants": [
{
"title": "Grant 500",
"id": "7ebd06d0-b921-11ed-936c-d5a40676ed46",
"size": 500,
"contested_percentage": 2
},
{
"title": "Grant 25K",
"id": "a75fb4c0-b921-11ed-936c-d5a40676ed46",
"size": 25000,
"contested_percentage": 98
}
]
},
"core_unit": {
"total": 173250,
"allocated": 0,
"available": 173250,
"contested": 0,
"contested_over_available_percentage": 0,
"contestants": []
},
"documentation": { …
```
=> feat: get expected allocated budget

src/modules/locations.ts, src/pages/submit/grant.tsx
=> feat: Grant forms' own url

package-lock.json, package.json, src/services/DiscordService.ts
=> feat: Crosspost to discord notifications

src/intl/en.json
=> fix: Added $ sign in the grants header

src/components/Category/CategoryBanner.css, src/components/Category/CategoryBanner.tsx
Category banner in proposals page was rendering as a link with cursor pointer style.
=> fix: category banner is now a link only when it is active and has href

src/components/Modal/ExternalLinkWarningModal.css, src/components/Modal/ExternalLinkWarningModal.tsx
=> fix: Link overflow & close warning modal when 'follow link' is clicked

src/entities/Proposal/outcome.test.ts, src/entities/Proposal/outcome.ts, src/entities/Proposal/outcomeUtils.ts, src/entities/Proposal/templates/messages.test.ts, src/entities/Proposal/utils.ts
=> feat: Added 'Abstain' as default option for voting

src/components/Home/MainBanner.css, src/components/Home/MetricsCard.css, src/components/Home/MetricsCard.tsx, src/components/Home/MetricsCards.css, src/components/Proposal/View/DetailsSection.css
=> feat: use card component in home metrics cards

src/components/Category/CategoryPill.tsx, src/components/Status/StatusPill.tsx, src/pages/proposal.tsx
=> feat: status and category pills are now links in proposal view

src/components/Status/ChoiceProgress.css
=> fix: Capitalize options first letter

src/entities/Proposal/routes.ts
=> chore: report create proposal error to rollbar

src/components/GrantRequest/GrantRequestFundingSection.tsx, src/pages/submit/grant.tsx
=> fix: grant submit when category changes

src/components/GrantRequest/CategorySection/SponsorshipSection.tsx
=> fix: sponsorship validation

src/components/GrantRequest/AddBudgetBreakdownModal.tsx, src/components/GrantRequest/AddModal.css, src/components/GrantRequest/AddTeamMemberModal.tsx, src/intl/en.json
=> feat: Added an optional label to the relevant link submission

src/clients/SnapshotGraphql.ts
=> fix: Home charts not displaying properly

src/components/GrantRequest/AddBudgetBreakdownModal.tsx
=> fix: funding left to disclose on edit

.github/workflows/heroku_database.yml
update HEROKU_TESTING_DB_URL to use repository workspace
=> chore: heroku db workflow tweaks

src/components/Grants/GrantCard/CliffProgress.tsx, src/components/Grants/GrantCard/VestingProgress.tsx, src/entities/Grant/utils.ts, src/intl/en.json, src/services/GrantsService.ts
Adding a couple of refactors as I was investigating this issue...
=> fix: vesting start date text on pending grants

src/components/Home/TopVoters.tsx, src/components/Modal/Votes/VoteListItem.tsx, src/components/Modal/Votes/VotesList.css, src/components/Modal/Votes/VotesList.tsx, src/constants.ts, src/hooks/useTopVoters.ts, src/intl/en.json, src/pages/proposal.tsx
=> feat: Hide votes with less than 5 VP

src/clients/DclData.ts
=> fix: wearable curation committee not showing in dropdown

src/components/Grants/CategorySelector.tsx, src/intl/en.json
=> feat: add grants category documentation link

static/api.yaml
Various enhancements to the swagger description texts
=> chore: updated summary descriptions

src/components/Proposal/View/Categories/GrantProposalView.tsx, src/components/Updates/UpdateMarkdownView.css
=> styles: match proposals and updates heading colors

src/components/Proposal/View/Budget/RequestedBudgetCard.tsx
=> feat: add 2 decimals to requested budget card

src/entities/Votes/routes.ts
=> fix: Wrong "active since" display

src/components/Proposal/View/Categories/GrantProposalView.tsx, src/components/Proposal/View/ProposalVoting/ProposalVotingSection.tsx, src/entities/Proposal/templates/grant.ts, src/entities/Proposal/types.ts, src/intl/en.json
=> feat: Added payment token in grants view

src/components/GrantRequest/GrantRequestFundingSection.tsx, src/components/GrantRequest/GrantRequestSectionCard.css, src/components/GrantRequest/GrantRequestSectionCard.tsx, src/components/Proposal/View/Budget/CategoryTotalCard.tsx, src/components/Proposal/View/Budget/RequestedBudgetCard.css, src/components/Proposal/View/Budget/RequestedBudgetCard.tsx
=> fix: Category card as link

src/components/Proposal/View/Budget/CompetingProposalsSidebar.css, src/components/Proposal/View/Budget/CompetingProposalsSidebar.tsx, src/components/Proposal/View/Budget/ProposalBudget.tsx, src/components/Proposal/View/ProposalCard.css
=> fix: proposal card icon not showing on long titles

package-lock.json, package.json, src/components/Category/CategoryList.tsx, src/components/Category/CategoryOption.tsx, src/components/Layout/Navbar.tsx, src/components/Search/CategoryFilter.tsx, src/components/Search/SearchInput.tsx, src/components/Search/SearchInputMobile.tsx, src/components/Search/SortingMenu.tsx, src/components/Search/StatusFilter.tsx, src/components/Search/TimeFrameFilter.tsx, src/hooks/useURLSearchParams.ts, src/pages/grants.tsx, src/pages/profile.tsx, src/pages/proposal.tsx, src/pages/proposals.tsx, src/pages/submit/governance.tsx, src/pages/submit/hiring.tsx, src/pages/submit/poi.tsx, src/pages/submit/update.tsx, src/pages/update.tsx
=> chore: update dcl-ui dep

package-lock.json, package.json
This PR upgrades the `decentraland-ui` package.
=> chore: Upgrade decentraland-ui package

src/components/Profile/VpDelegationBox.tsx
=> fix: 0 rendered on delegated vp to box

src/pages/proposal.tsx
=> fix: non active grants not showing category

src/components/Proposal/View/ProposalThresholdsSummary.css, src/components/Proposal/View/ProposalThresholdsSummary.tsx
=> fix: proposal thresholds margin style

src/components/Proposal/View/BiddingAndTenderingProcess.tsx, src/components/Proposal/View/Budget/CompetingProposalsSidebar.css, src/components/Proposal/View/GovernanceProcess.tsx, src/components/Proposal/View/ProposalProcess.css, src/components/Proposal/View/ProposalProcess.tsx, src/entities/Proposal/utils.ts, src/intl/en.json, src/pages/proposal.tsx, src/theme.css
=> feat: add governance process component

src/components/Grants/GrantCard/GrantCard.tsx, src/components/Proposal/Update/CollapsedProposalUpdate.tsx, src/components/Proposal/Update/ProposalUpdate.tsx
=> fix: descendant error in proposal update

gatsby-browser.js, src/components/Category/CategoryBanner.css, src/components/GrantRequest/BreakdownAccordion.tsx, src/components/GrantRequest/BudgetBreakdownConcept.css, src/components/GrantRequest/BudgetInput.css, src/components/GrantRequest/NumberSelector.css, src/components/GrantRequest/TeamMemberItem.css, src/components/Grants/GrantsPastItem.css, src/components/Modal/VotingPowerDelegationDetail/CandidateDetails.css, src/components/Modal/VotingPowerDelegationDetail/CandidateDetails.tsx, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Proposal/View/Budget/ContestedBudgetCard.css, src/components/Proposal/View/Budget/ContestedBudgetLabel.css, src/components/Proposal/View/ProposalCard.css, src/components/User/Badges/BadgeCard.css, src/components/User/Badges/BadgeStack.css, src/components/User/Badges/BadgeWithTitle.css, src/theme.css, src/ui-overrides.css
=> refactor: update colors naming and clean css code

src/components/Proposal/View/ProposalVoting/ChoiceButton.css, src/components/Proposal/View/ProposalVoting/ChoiceButton.tsx, src/components/Transparency/MonthlyTotal.css, src/components/Transparency/MonthlyTotal.tsx
=> fix: transparency styles

src/components/Category/CategoryOption.tsx, src/components/Common/Typography/Link.tsx
=> fix: links not opening in new window

src/components/BidRequest/CardSubtitle.css, src/components/BidRequest/CardSubtitle.tsx, src/components/GrantRequest/GrantRequestSectionCard.css, src/components/Icon/CheckCircleOutline.tsx, src/entities/Proposal/outcomeUtils.ts, src/hooks/useProjectRequestSectionNumber.ts, src/hooks/useProposalOutcome.ts, src/hooks/useProposalVotes.ts, src/intl/en.json, src/pages/submit/bid.css, src/pages/submit/bid.tsx, src/pages/submit/grant.tsx
=> feat: add parent proposals in bid form

src/components/Category/CategoryPill.tsx, src/components/Common/Pill.tsx, src/components/Delegation/DelegatesTable.css, src/components/Delegation/DelegatesTableRow.css, src/components/Delegation/DelegatesTableRow.tsx, src/components/Delegation/VotingPowerListModal.css, src/components/Grants/GrantPill.tsx, src/components/Home/OpenProposal.tsx, src/components/Modal/Votes/VotesList.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.css, src/components/Modal/VotingPowerDelegationDetail/VotingPowerDelegationDetail.tsx, src/components/Profile/CoAuthorPill.tsx, src/components/Profile/ProposalCreatedItem.css, src/components/Profile/ProposalCreatedItem.tsx, src/components/Proposal/ProfileProposalItem.tsx, src/components/Proposal/Update/CollapsedProposalUpdate.tsx, src/components/Proposal/Update/ExpandedProposalUpdate.tsx, src/components/Proposal/Update/ProposalUpdate.css, src/components/Proposal/View/Budget/RequestedBudgetCard.tsx, src/components/Proposal/View/VestingContract.tsx, src/components/Status/StatusPill.css, src/components/Status/StatusPill.tsx
Closes #1081 
Closes #1079 
Closes #1080
=> fix: delegation, proposal updates and pills styles and improvements

src/entities/Proposal/jobs.test.ts, src/entities/Proposal/jobs.ts, src/entities/Proposal/outcome.test.ts, src/entities/Proposal/outcome.ts, src/entities/Proposal/testHelpers.ts
=> feat: finish bid proposals

package-lock.json, package.json, src/components/Proposal/Submit/ProposalSubmitCatalystPage.tsx, src/entities/Proposal/routes.ts, src/entities/Proposal/utils.ts, src/pages/submit/ban-name.tsx
=> fix: Replace deprecated endpoint

src/entities/Updates/utils.ts
Passed grant can't create updates
Until enacted
=> feat: remove passed grants update creation

package-lock.json, package.json
=> chore: update decentraland gatsby

src/pages/proposal.tsx
Added address and proposal id to see if we can learn something from all this votes without enough VP
=> chore: add extra info to voting error report

src/migrations/1688741539692_create-bids-table.ts
This reverts commit 04018265d73ec94ba480d73a335b8ca94e8061ac.
=> Revert "chore: remove extension from bids migration (#1147)"

src/back/routes/badges.ts, src/clients/Governance.ts, src/clients/OtterspaceSubgraph.ts, src/components/Debug/BadgesAdmin.tsx, src/entities/Badges/types.ts, src/entities/Badges/utils.ts, src/pages/debug.css, src/services/BadgesService.ts
=> chore: revoke badges

README.md, scripts/clean-db.sh
- Update clean-db.sh script with users and unpublished bids
- Update readme
=> chore: update db dump

src/components/Transparency/MemberCard.css, src/components/Transparency/MemberCard.tsx, src/components/Transparency/MembersSection.tsx
=> feat: transparency profiles go to profile page

src/components/Proposal/View/CalendarAlertButton.css, src/components/Proposal/View/CalendarAlertButton.tsx
=> fix: calendar button icon size

src/back/jobs/BadgeAirdrop.ts, src/back/models/AirdropJob.ts, src/back/routes/badges.ts, src/back/types/AirdropJob.ts, src/back/utils/contractInteractions.ts, src/clients/Governance.ts, src/clients/OtterspaceSubgraph.ts, src/entities/Badges/storeBadgeSpec.ts, src/entities/Badges/types.ts, src/entities/Badges/utils.ts, src/hooks/useTopVoters.ts, src/migrations/1692114399675_create-airdrop-jobs-table.ts, src/services/BadgesService.ts
- Check for existing badge specs before creating spec
- Retry badge spec upload and badge spec creation
=> chore: top voters badge pt3

package-lock.json, package.json, src/clients/VestingData.ts
=> chore: replace web3 for ethers

src/back/jobs/BadgeAirdrop.ts, src/clients/OtterspaceSubgraph.ts, src/components/User/Badges/Badge.css, src/components/User/Badges/Badge.tsx, src/entities/Badges/storeBadgeSpec.ts, src/entities/Badges/types.ts, src/services/BadgesService.ts, src/utils/date/toIsoString.test.ts, src/utils/date/toIsoString.ts
=> chore: show expired badges considering spec expiration date

src/services/BadgesService.ts
=> fix: Badge airdrops in series

src/entities/Badges/types.ts, src/services/BadgesService.ts
fix: run revoke/reinstate serially
chore: hide revoked badges with reason `Other`
=> fix: serial badge actions

src/clients/SnapshotGraphql.ts
=> fix: add missing query param name

src/back/routes/votes.ts, src/components/Common/BoxTabs.css, src/components/Home/OpenProposals.css, src/components/Profile/ActivityBox.tsx, src/components/Profile/GrantBeneficiaryBox.tsx, src/components/Profile/VotedProposalsBox.tsx, src/components/Profile/VpDelegationBox.tsx, src/components/Profile/VpDelegatorsBox.tsx, src/components/User/UserStats.css, src/components/User/UserStats.tsx, src/pages/profile.css, src/pages/profile.tsx
=> feat: Wide profile page

src/components/Category/CategoryPill.tsx, src/components/Common/Pill.css, src/components/Common/Pill.tsx, src/components/FloatingBar/FloatingBar.css, src/components/Home/BottomBanner/BottomBanner.css, src/components/Home/MainBanner.css, src/components/Projects/Current/ProjectsBanner.css, src/components/Proposal/HeroBanner.css, src/components/Proposal/HeroBanner.tsx, src/components/Proposal/ProposalHero.css, src/components/Proposal/ProposalHero.tsx, src/components/Proposal/View/ProposalProcess.css, src/components/Status/StatusPill.tsx, src/pages/proposal.css, src/pages/proposal.tsx, src/pages/submit/submit.css, src/theme.css
Closes #1275 
- Hero banner for active proposal types, white Pill & transparent pill
- Rejected/Passed/Finished
- Long text
=> feat: proposal hero

src/components/Transparency/MonthlyTotal.css, src/components/Transparency/MonthlyTotal.tsx, src/pages/transparency.css, src/pages/transparency.tsx
=> feat: wider transparency page

src/entities/Proposal/types.ts, src/pages/submit/draft.tsx
=> fix: draft title validation

src/components/FloatingBar/FloatingBar.css, src/components/GrantRequest/GrantRequestSectionCard.css, src/components/Icon/Forum.tsx, src/components/Layout/ContentLayout.css, src/components/Layout/Navigation.css, src/components/Proposal/HeroBanner.css, src/components/Proposal/ProposalHero.css, src/components/Proposal/View/Categories/BidProposalView.tsx, src/components/Proposal/View/Categories/GrantProposalView.tsx, src/components/Proposal/View/ProposalDescriptionItem.tsx, src/components/Proposal/View/ProposalMarkdown.css, src/components/Proposal/View/ProposalMarkdown.tsx, src/components/Search/SearchInputMobile.css, src/components/Token/TokensPerWalletPopup.css, src/pages/proposal.css, src/pages/proposal.tsx, src/pages/transparency.css, src/ui-overrides.css
Closes #1278 
- Responsive 2 column design
- Fixed issue with long links or addresses on mobile view
=> feat: wider proposal view

src/components/Category/CategoryPill.tsx, src/components/Common/Pill.css, src/components/FloatingBar/FloatingBar.tsx, src/components/FloatingHeader/FloatingHeader.css, src/components/FloatingHeader/FloatingHeader.tsx, src/components/Proposal/ProposalHero.tsx, src/components/Proposal/ProposalSidebar.css, src/components/Proposal/View/Budget/ProposalBudget.css, src/components/Proposal/View/DetailsSection.css, src/components/Proposal/View/ProposalMarkdown.css, src/components/Status/StatusPill.tsx, src/pages/proposal.css, src/pages/proposal.tsx
=> feat: proposal scroll down heading

src/components/FloatingHeader/FloatingHeader.tsx, src/components/Layout/Desktop1200.tsx, src/components/Proposal/Breadcrumb.css, src/components/Proposal/Breadcrumb.tsx, src/components/Proposal/ProposalHero.css, src/components/Proposal/ProposalHero.tsx, src/intl/en.json
=> feat: proposal breadcrumbs

src/entities/Badges/types.ts
=> fix: add ReinstatedByUser badge status reason

src/components/Home/ActiveCommunityGrants.css, src/components/Projects/Current/CurrentProjectsList.css, src/components/Projects/Current/CurrentProjectsList.tsx, src/components/Projects/ProjectCard/ProjectCard.css, src/pages/projects.tsx
=> fix: project lists containers size

src/components/Debug/SnapshotStatus.tsx
=> fix: snapshot status client ping

src/pages/proposals.css, src/pages/proposals.tsx
First load on proposals for build seems to work, will test on review app
Mobile looks good:
Filters working
=> fix: change NotMobile tags order

src/components/Common/Username.css, src/components/Delegation/DelegatorCardProfile.css, src/components/Delegation/DelegatorCardProfile.tsx
=> fix: delegator card profile styles

src/pages/projects.tsx
**Related issues**
Fixes #1339 (Again)
=> fix: empty projects state

src/back/routes/proposal.ts, src/clients/DclData.ts, src/clients/Governance.ts, src/components/Profile/GrantBeneficiaryItem.tsx, src/services/ProjectService.ts, static/api.yaml
=> feat: remove grants endpoint

src/components/Profile/GrantBeneficiaryItem.tsx
=> fix: grant card budget display

src/components/User/Badges/BadgeCard.tsx, src/components/User/Badges/Badges.css, src/components/User/Badges/Badges.tsx, src/components/User/Badges/BadgesSidebar.tsx, src/intl/en.json
=> fix: past badges in profile

src/utils/projects.ts
=> fix: projects funding total not showing

src/back/routes/votes.ts, src/clients/Governance.ts, src/components/Charts/ProposalVPChart.tsx, src/components/Charts/ProposalVPChart.utils.ts, src/components/Common/ProposalPreviewCard/ProposalPreviewCard.tsx, src/components/Common/ProposalPreviewCard/VoteModule.tsx, src/components/Home/OpenProposals.tsx, src/components/Modal/Votes/VotesList.tsx, src/components/Profile/ProposalCreatedItem.tsx, src/components/Proposal/ProposalItem.tsx, src/components/Proposal/ProposalSidebar.tsx, src/components/Proposal/SentimentSurvey/SurveyResults.tsx, src/components/Proposal/View/ProposalCard.tsx, src/components/Proposal/View/ProposalGovernanceSection.tsx, src/components/Proposal/View/ProposalVoting/ProposalVotingSection.tsx, src/entities/Proposal/templates/messages.ts, src/entities/Votes/types.ts, src/entities/Votes/utils.ts, src/hooks/useProposalVotes.ts, src/hooks/useProposalsVotes.ts, src/hooks/useSurvey.ts, src/hooks/useVotesCountByDate.ts, src/pages/proposal.tsx, src/pages/proposals.tsx, src/utils/votes/helpers/DelegationsLabelBuilder.ts, src/utils/votes/helpers/VotedChoiceBuilder.ts, src/utils/votes/utils.test.ts, src/utils/votes/utils.ts
=> fix: Vote segmentation

src/components/Modal/WalletSelectorModal.tsx
=> fix: metamask deeplink

src/components/Proposal/View/AuthorDetails.tsx, src/components/Proposal/View/GrantCard.css, src/components/Proposal/View/GrantCard.tsx, src/components/Proposal/View/GrantCardList.tsx, src/intl/en.json
=> feat: add grant requests to author details

package-lock.json, package.json
This reverts commit eae5077fc808936578cb21a78c1775680bc52df6.
=> Revert "chore(deps): bump sharp from 0.30.7 to 0.32.6 (#1426)"

src/back/routes/votes.ts, src/back/services/vote.test.ts, src/back/services/vote.ts, src/clients/Governance.ts, src/components/Home/TopVoters.tsx, src/hooks/useTopVoters.ts, src/services/BadgesService.ts, src/services/CacheService.ts, static/api.yaml
First request
Following requests from different client:
Added endpoint to api docs
Closes #1417
=> chore: top voters cache

src/entities/Proposal/utils.ts, src/hooks/useProposalsSearchParams.ts, src/pages/proposals.tsx
No filter
Type
Subtype
Status
Timeframe
Searching
Mobile
Closes #1444
=> chore: hide priority widget on search

src/services/ProjectService.ts, src/services/VestingService.ts
=> chore: cache transparency vesting data

src/constants.ts, src/utils/filesystem.ts
Fix `NEW_ROLLOUT` variable calculation
=> fix NEW_ROLLOUT validation

src/components/Home/ActivityTicker.css, src/components/Home/ActivityTicker.tsx
=> feat: add hover to activity ticker item

.github/workflows/heroku_build.yml
=> chore: heroku_build gh action

src/components/BidRequest/CardSubtitle.tsx, src/entities/Proposal/outcomeUtils.ts
=> fix: VP decimals

gatsby-config.js, package-lock.json, package.json, src/components/Layout/LogIn.tsx, src/pages/submit/update.tsx
This PR change the way the users login into the platform by redirecting them to the Auth dApp when needed.
The PR adds as well a proxying mechanism to be able to log in successfully while developing the governance dApp.
E.g: *Closes/Fixes #0000*
=> feat: Use auth dApp to log in

.github/workflows/heroku_review_app_create.yml
Based on https://gist.github.com/hopsoft/ac014e0efc7bfc1dbdb19ff7a66c5274
=> chore: action for creating heroku review apps

src/components/Form/MarkdownFieldSection.tsx, src/components/Layout/ContentLayout.tsx, src/components/Layout/ContentSection.css, src/components/Layout/ContentSection.tsx, src/components/ProjectRequest/ProjectRequestSection.tsx, src/components/Updates/FinancialSection.tsx, src/components/Updates/GeneralSection.tsx, src/components/Updates/SummaryContent.css, src/components/Updates/SummaryContent.tsx, src/components/Updates/UpdateMarkdownView.tsx, src/pages/submit/update.css, src/pages/submit/update.tsx, src/ui-overrides.css
=> feat: update submit update layout

src/components/User/UserStats.tsx
=> feat: change badges position in profile

package-lock.json, package.json, src/components/Layout/Layout.tsx
Integration of the new [Navbar2](https://ui.decentraland.org/?path=/story/navbar2--with-notification-pending)
=> feat: Narbar2 integration

src/components/Common/Typography/Text.tsx, src/components/Updates/SummaryContent.tsx
=> fix: Title attribute

src/back/routes/badges.ts, src/clients/Governance.ts, src/clients/OtterspaceSubgraph.ts, src/clients/utils.ts, src/components/Proposal/View/SidebarLinkButton.tsx, src/components/Transparency/CoreUnitCard.css, src/components/Transparency/CoreUnitCard.tsx, src/components/Transparency/CoreUnitsSection.css, src/components/Transparency/CoreUnitsSection.tsx, src/components/Transparency/Sidebar.css, src/components/Transparency/Sidebar.tsx, src/components/User/Badges/Badge.css, src/components/User/Badges/Badge.tsx, src/constants.ts, src/entities/Badges/types.ts, src/hooks/useCoreUnitsBadges.ts, src/intl/en.json, src/pages/transparency.css, src/pages/transparency.tsx, src/services/BadgesService.ts
=> feat: transparency core units

package-lock.json, package.json
=> chore: upgrade decentraland-gatsby to 5.98.1

src/back/services/notification.ts
Notifications enabled and no PK (server does not crash)
Notifications disabled
Notifications enabled and PK
=> fix: disable notifications when pk is not present

package-lock.json, package.json
Update decentraland-ui with navbar fix
E.g: *Closes/Fixes #0000*
=> feat: update decentraland-ui

src/components/User/Badges/BadgeCard.css, src/components/User/Badges/BadgeCard.tsx
=> fix: Badge image size

src/components/Home/OpenProposals.tsx
=> fix: participating vp tab votes not being counted

src/back/routes/project.ts, static/api.yaml
=> feat: Projects api docs

src/components/LegislativeTracker.css, src/components/LegislativeTracker.tsx, src/intl/en.json, src/pages/proposals.tsx
Texts TBD with @ginocingolani 
Closes #866
=> feat: add legislative tracker button

src/utils/Catalyst/index.ts
=> feat: Display guest names

src/components/Home/BottomBanner/Action.css
=> fix: newsletter button styles in bottom banner

src/back/routes/update.ts, src/clients/Governance.ts, src/entities/Updates/types.ts, src/pages/submit/update.tsx
=> fix: Update submission bug

gatsby-browser.js, package-lock.json, package.json, src/components/Layout/Layout.tsx
Part of https://github.com/decentraland/growth/issues/140
=> feat: bump decentraland-gatsby and ui

src/components/Updates/FinancialCardsSection.tsx, src/components/Updates/FinancialSection.tsx, src/components/Updates/UpdateMarkdownView.tsx, src/entities/Updates/utils.ts, src/pages/submit/update.tsx, src/pages/update.tsx
=> fix: Funds released on posted updates

src/back/routes/budget.ts, src/entities/QuarterBudget/model.test.ts, src/entities/QuarterBudget/model.ts, src/services/BudgetService.ts
=> feat: New all budgets endpoint

src/back/routes/debug.ts, src/clients/Governance.ts, src/components/Debug/InvalidateCache.tsx, src/pages/debug.tsx, src/services/CacheService.ts
=> feat: Invalidate cache

src/components/Updates/UpdateMarkdownView.tsx
=> fix: Update last edited

src/back/routes/events.ts, src/back/routes/webhooks.ts, src/back/services/events.ts
=> chore: move discourse webhook

src/components/Common/Pill.css, src/components/Common/Pill.tsx, src/components/Icon/Check.tsx, src/components/Icon/Cross.tsx, src/components/Icon/Pause.tsx, src/components/Profile/GrantBeneficiaryItem.css, src/components/Profile/GrantBeneficiaryItem.tsx, src/components/Profile/VestingPill.tsx, src/components/Proposal/View/ProposalCoAuthorStatus.tsx, src/components/Proposal/View/ProposalDetailCoauthors.tsx, src/components/Search/FilterMenu.tsx, src/components/Search/SearchInputMobile.tsx
=> feat: Vesting pill

src/components/Home/ActiveCommunityGrants.css, src/components/Home/ActiveCommunityGrants.tsx, src/components/Projects/ProjectCard/ProjectCard.css
=> fix: sidebar push

package-lock.json, package.json
=> feat: update dcl gatsby to latest version

src/back/models/Event.ts, src/back/routes/events.ts, src/back/services/events.ts, src/clients/Governance.ts, src/components/Debug/QueryData.tsx, src/pages/debug.tsx
=> chore: all events route

src/components/Category/CategoryPill.tsx, src/components/Common/Pill.tsx, src/components/Status/StatusPill.tsx
=> refactor: pill now receives href

src/back/services/notification.ts, src/entities/Proposal/jobs.test.ts, src/utils/notifications.ts
=> fix: change messages and add missing proposal title + mini refactor

src/components/Profile/GrantBeneficiaryItem.css
=> fix: grant beneficiary item styles

src/components/Proposal/ProposalHeaderPoi.css, src/components/Proposal/ProposalHeaderPoi.tsx, src/components/Proposal/ProposalHeaderPoiImage.css, src/components/Proposal/ProposalHeaderPoiImage.tsx
=> refactor: remove ImgFixed use

src/components/Layout/Layout.tsx
=> refactor: replace useChainId and useAsyncState uses

package-lock.json, package.json, src/components/Proposal/ProposalHeaderPoi.tsx, src/components/Proposal/Submit/ProposalSubmitCatalystPage.tsx, src/entities/Proposal/utils.ts, src/utils/Catalyst/index.ts
=> refactor: remove catalyst function use

src/components/Sidebar/GovernanceSidebar.css, src/components/Sidebar/Overlay.css, src/components/User/Badges/Badge.css
=> fix: navbar over sidebar + badge background color

src/back/models/Event.ts, src/back/services/events.ts, src/back/services/notification.ts, src/components/Events/ProjectUpdateCommentedEvent.tsx, src/components/Events/ProposalRelatedEvent.tsx, src/components/Events/utils.ts, src/components/Home/ActivityTicker.tsx, src/intl/en.json, src/migrations/1706037450493_events-delegation-types.ts, src/migrations/1707416989780_events-update-commented-type.ts, src/shared/types/events.ts
=> feat: events for comments on project updates

src/back/services/discord.ts, src/back/services/events.ts, src/components/Charts/ProposalVPChart.utils.ts, src/components/Comments/Comment.tsx, src/components/Common/Username.tsx, src/components/Events/DelegationEvent.tsx, src/components/Layout/Layout.tsx, src/components/Proposal/View/AuthorDetails.tsx, src/components/User/UserAvatar.tsx, src/hooks/useDclProfile.ts, src/pages/profile.tsx, src/utils/Catalyst/index.ts, src/utils/Catalyst/types.ts
=> refactor: replace useProfileInjected

src/back/models/Event.ts, src/back/routes/events.ts, src/back/services/events.ts, src/back/utils/validations.test.ts, src/back/utils/validations.ts, src/shared/types/events.ts
This reverts commit 8a867459c936016905afa88464072e3d9bbbe224.
=> Revert "feat: Filter activity (#1605)"

src/back/routes/votes.ts, src/clients/API.ts, src/clients/ApiResponse.ts, src/clients/Discourse.ts, src/clients/Governance.ts, src/clients/SnapshotGraphql.ts, src/clients/base64.ts, src/components/Home/ActiveCommunityGrants.tsx, src/pages/projects.tsx
=> chore: remove dcl gatsby API from frontend

src/clients/utils.ts, src/components/Common/Typography/Link.tsx, src/components/Layout/Head.tsx, src/components/Layout/Layout.tsx, src/components/Modal/CalendarAlertModal.tsx, src/components/Modal/IdentityConnectModal/AccountsConnectModal.tsx, src/components/Proposal/ProposalSidebar.tsx, src/helpers/browser.ts, src/hooks/useAnalyticsTrack.ts, src/hooks/useAnalyticsTrackLink.ts, src/hooks/useAsyncTask.ts, src/hooks/useDiscordConnect.ts, src/hooks/useForumConnect.ts, src/hooks/useValidationSetup.ts, src/utils/analytics.ts
=> refactor: remove useTrackContext and useTrackLinkContext

src/components/Common/ProposalPreviewCard/ProposalPreviewCard.css
=> fix: proposal preview card variant vote gap

src/components/Home/ActivityTickerFilter.css, src/components/Home/ActivityTickerFilter.tsx, src/intl/en.json
Upside arrow
Hover over button, no activity text
=> fix: minor changes & fixes to filter

src/components/Home/ActivityTickerFilter.css, src/components/Home/ActivityTickerFilter.tsx, src/theme.css
=> fix: filter box over loader, leave filters counter on filtering

src/components/Home/ActivityTickerFilterItem.css
=> fix: add css class filter to checkbox style

src/back/jobs/BadgeAirdrop.ts, src/back/types/AirdropJob.ts, src/back/utils/contractInteractions.ts, src/services/BadgesService.ts
Closes #1673 
Included recipients and badge spec id data on the airdrop outcome:
=> chore: report failed airdrop jobs

src/hooks/useSurvey.ts, src/pages/proposal.tsx
=> refactor: modules reorder

src/components/Layout/Navigation.css, src/components/Layout/Navigation.tsx
=> feat: navigation component as nav

package.json, src/clients/Governance.ts
Rollbacked changes and modified url
=> fix: api url for .vote

src/components/Comments/Comment.tsx
=> fix: Hide comma when is no necessary

src/components/Layout/Navigation.tsx
=> feat: hide governance notifications bell

src/back/models/Financial.ts, src/back/routes/update.ts, src/services/FinancialService.ts, static/api.yaml
=> feat: Financial records endpoint

src/components/Modal/IdentityConnectModal/AccountsConnectModal.tsx, src/intl/en.json
=> feat: add helper text to push card

src/components/Common/Typography/Heading.css, src/components/Profile/Bio.css, src/components/Profile/Bio.tsx, src/components/User/UserStats.tsx, src/intl/en.json, src/pages/profile.tsx, src/utils/Catalyst/types.ts
=> feat: Profile bio

src/back/services/dcl-notification.ts, src/back/services/events.ts, src/back/services/notification.ts, src/shared/types/notifications.ts, src/utils/notifications.ts
=> feat: Project update comment notification

package-lock.json, package.json, src/components/Layout/Layout.tsx, src/components/Modal/IdentityConnectModal/AccountsConnectModal.tsx, src/components/Notifications/Notifications.tsx, src/components/Notifications/NotificationsFeed.tsx, src/front/context/useAuth.utils.ts, src/helpers/index.ts, src/hooks/usePushSubscriptions.ts, src/utils/contracts/index.ts, src/utils/notifications.ts
This PR upgrades dependencies to support `polygon amoy` testnet and updates the `polygon mumbai` references to `polygon amoy`.
=> feat: Upgrade packages to support polygon amoy testnet

src/back/routes/user.ts
Closes #1778 maybe
Errors are getting empty to rollbar so this might help with figuring out what's wrong
=> chore: use request errors on getProfile user route

package.json, src/back/models/ProjectMilestone.ts, src/migrations/1715085519126_create-project-milestones-table.ts, src/migrations/1716383233795_milestone-delivery-date.ts, src/services/ProjectService.ts
=> feat: create project milestones from proposal data

src/back/models/Project.ts, src/clients/Transparency.ts, src/clients/VestingData.ts, src/entities/Bid/types.ts, src/entities/Grant/types.ts, src/services/ProjectService.ts, src/utils/errorCategories.ts, src/utils/projects.ts
=> chore: update project status with vesting

src/entities/Proposal/utils.ts, src/services/ProjectService.ts
=> feat: add proposal link as project link

src/back/routes/update.ts, src/back/utils/validations.ts
Part of https://github.com/decentraland/governance-ui/issues/56#issue-2321233654
=> feat: Not editable project status

src/back/jobs/BadgeAirdrop.ts, src/server.ts
=> chore: update chron schedules so jobs don't overlap

src/clients/VestingData.ts
=> fix: DAO Vesting contract not beeing displayed

src/back/routes/user.ts, src/back/services/user.ts
=> fix: return empty profile instead of throwing errors

src/back/utils/contractInteractions.ts, src/entities/Badges/utils.ts, src/entities/Snapshot/utils.ts, src/services/BadgesService.test.ts, src/services/BadgesService.ts
Optimize user classification for badge actions & reuse signer and contract for gas estimation and badge txs
=> chore: improve landowner badges job cpu usage

README.md
=> chore: README.md update

src/entities/User/model.ts, src/routes/user.ts, src/services/user.ts
=> feat: unlink accounts

src/clients/VestingsSubgraph.ts, src/constants.ts, src/entities/Proposal/jobs.ts, src/entities/Proposal/model.ts, src/entities/Proposal/types.ts, src/server.ts, src/services/ProposalService.ts, src/services/VestingService.ts, src/services/notification.ts, src/utils/notifications.ts
Closes #1883 
Query works for vesting addresses:
Subgraph query works for vestings (using period of a month):
Unique contributors OK
=> chore: cliff ending soon notification
