decentraland/governance

src/components/Modal/VoteListItem.tsx
src/components/Modal/VotesList.css
src/components/Modal/VotesList.tsx
src/components/Section/DetailsSection.css
src/components/Section/ProposalResultSection.tsx
src/entities/Votes/utils.ts
src/intl/en.json
src/pages/proposal.tsx

This PR implements:
- see votes button to see the list of votes.
- A modal to show the list of votes.
- inside the modal, you will see the address, the vote and vp of the user that voted
- link to users VP page.
[issue 135](https://github.com/decentraland/governance/issues/135)
ps: I added this abbreviateNumber function because when the modal is in mobile screens if the number is high will break the text to another line even if the font is smaller in snapshot they do the same if you look at the screenshot.

Add List of Voters on Proposal Page

---

src/components/Subscription/SubscriptionBanner.tsx

This PR addresses [this issue](https://github.com/decentraland/governance/issues/163)
Subscription banner is shown once loaded & only if needed
While loading account data
Once loaded

163 - Hide newsletter alert

---

README.md
src/components/Section/DetailItem.css
src/components/Transparency/MonthlyTotal.css
src/components/Transparency/MonthlyTotal.tsx
src/intl/en.json
src/pages/transparency.css
src/pages/transparency.tsx

Card 2 bigger
Card 1 bigger
Mobile View
Previously:
Now:
Mobile view
Previously:
Now:
Tablet
Mobile view with long texts

Transparency monthly total fix

---

src/api/DclData.ts
src/components/Transparency/MemberCard.css
src/components/Transparency/MemberCard.tsx
src/components/Transparency/MembersSection.tsx

* Remove addresses from the members list.
* Render the avatar using the URL directly.
Looks like this:

Remove addresses from transparency page

---

src/components/Search/SearchInput.tsx
src/components/Search/SearchTitle.css
src/components/Search/SearchTitle.tsx
src/components/Search/SortingMenu.tsx
src/intl/en.json

This PR can be tested [here](http://pr217.test.decentraland.vote/)
- Removed autofocus to the search input on page load
- Changed displayed search title
Example for short text
Example for long text
In mobile:
- Fix to sorting menu in mobile view (tx to @ncomerci )

Search improvements & minor fixes

---

src/components/Category/CategoryLabel.tsx

Fix: Underscore removed on category labels

---

src/components/Proposal/ProposalComments.css
src/components/Proposal/ProposalComments.tsx
src/entities/Discourse/utils.test.ts
src/entities/Discourse/utils.ts
src/entities/Proposal/types.ts
src/intl/en.json

This PR closes [this issue](https://github.com/decentraland/governance/issues/199)
Ready to be tested at: http://pr199.test.decentraland.vote/
When comments are equal or less than 3, it reads "Join the discussion"
When there are more than 3 comments available for display, it changes to "Read More"
With several comments
when opened:
Made some tweaks to mobile font sizes:
when opened:

199 - Add button to show all comments on proposal

---

src/components/Transparency/MonthlyTotal.tsx
src/pages/transparency.tsx

This PR closes [this issue](https://github.com/decentraland/governance/issues/268)
It can be [tested here](http://pr269.test.decentraland.vote/transparency/)
- Positive income difference shows green, positive expenses difference shows red
- Negative income difference shows red, negative expenses difference shows green

Make number colors configurable for MonthlyTotal

---

src/pages/submit/draft.tsx
src/pages/submit/governance.tsx

Quick fix. We should check later why adding those variables as dependencies are causing re-renders.

fix: re-render in draft promotion forms

---

src/entities/Proposal/routes.ts

Closes [issue](https://github.com/decentraland/governance/issues/337)
Fix: use update message creation date instead of proposal creation date

Proposal status update date fix

---

src/pages/proposal.css

fix: max image size in proposals

---

src/entities/Proposal/templates/index.ts
src/pages/proposal.tsx

fix: show updates on enacted grants and use last 7 chars of snapshot id on discourse title

---

src/components/Charts/LineChart.tsx
src/components/Home/Charts.css
src/components/Home/Charts.tsx
src/entities/Snapshot/utils.ts

Firefox is not supporting date parsing without the day

fix: line charts date display bug in firefox

---

src/components/Delegation/DelegatorCardProfile.tsx
src/components/Grants/GrantBeneficiaryItem.tsx
src/components/Icon/ChevronRightCircleOutline.css
src/components/Icon/ChevronRightCircleOutline.tsx

It can be set to a fixed size, or it can resize preserving proportions.
It changes opacity on hover
And it's family friendly

feat: chevron right circle outline svg

---

src/clients/SnapshotGraphql.ts
src/clients/SnapshotGraphqlTypes.ts
src/components/Home/DaoDelegates.tsx
src/components/Section/ProposalVoting/DelegationsLabel.tsx
src/entities/Votes/routes.ts
src/entities/Votes/utils.ts
src/hooks/useVotingPowerDistribution.ts
src/hooks/useVotingPowerInformation.ts
src/hooks/useVotingPowerOnProposal.ts
src/modules/contracts/index.ts
src/modules/votes/utils.ts

Update `updateSnapshotProposalVotes` and `useVotingPowerOnProposal` to stop using `snapshot.utils.getScores`
Things are looking OK in Goerliland
Account 1 with 1k VP, delegated to account 2
Account 2 with 200vp, delegated to account 3 (and overruled vote)
Account 3 with 350vp

Update votes and vp on proposal snapshot endpoint

---

src/migrations/1663608324933_add-coauthors-to-core-units-grants.ts

This fixes migration running on a blank database (local or review apps).

chore: comment coauthors to core units migration

---

src/components/Status/Progress.css

fix: rename progress bar for status 4

---

src/entities/Proposal/model.ts
src/entities/Proposal/types.ts

When the query param `coauthor=true` is added to the `/proposals` endpoint, the list of approved co-authors (if any) is displayed.
This is a required modification in order to display the list of coauthors in the transparency proposals sheet.

feat: Added coauthors list option to proposals API endpoint

---

src/pages/proposal.css

fix: images not resizing and overlapping with sidebar (#718)

---

src/components/Status/LeadingOption.tsx
src/components/Status/StatusMenu.tsx
src/components/Status/StatusPill.tsx
src/entities/Budget/routes.ts
src/entities/Proposal/model.ts
src/entities/Proposal/routes.ts
src/entities/Proposal/templates/messages.test.ts
src/entities/Proposal/templates/messages.ts
src/entities/Proposal/types.ts
src/entities/Proposal/utils.test.ts
src/entities/Proposal/utils.ts
src/hooks/useSearchParams.ts
src/intl/en.json
src/pages/proposal.tsx

Not sure if we should be able to link grant proposals with OOB status, but if the idea is to be able to resubmit and link to them, I think we should.
Moved frontend behavior depending on `ProposalStatus` to tested functions in `utils.ts`, so it's easier to refactor them later.

feat: add out of budget to proposal status

---

src/pages/proposal.css

fix: Break line when '\n' in proposals description

---

.env.example
src/entities/Discourse/utils.test.ts
src/entities/Discourse/utils.ts

Now it uses the forum URL to generate the url when the user has a custom avatar set, like https://forum.decentraland.vote/user_avatar/forum.decentraland.vote/lemu/45/5_2.png
If the user does not have a custom avatar, uses the url provided by discourse:
https://avatars.discourse-cdn.com/v4/letter/1/ec9cab/45.png

chore: get avatars from forum

---

src/entities/Proposal/outcome.test.ts
src/entities/Proposal/outcome.ts

fix: Outcome calculation for proposals with legacy options

---

src/components/Proposal/View/Budget/ProposalBudget.tsx
src/components/Proposal/View/Budget/RequestedBudgetCard.tsx
src/intl/en.json
src/pages/proposal.tsx

Closes #923 
Display requested budget and grant category card on all finished/rejected/passed/enacted grants

feat: display budget and category on all finished grants

---

src/pages/proposal.tsx

fix: hide survey topics on proposals created before 2023/04/05

---

src/components/Proposal/View/ProposalPromotionSection.tsx

Polls are promotable
Pitch proposals are not

fix: disable promotion button only for pitch and tender proposals

---

src/components/Proposal/CategoryAssessment.css
src/components/Proposal/CategoryAssessment.tsx

Changed heading styles to be smaller (so they are not much bigger than the section title) and title weights to match proposal sections titles

Fix: category assessment markdown

---

package-lock.json
package.json
src/components/Modal/WalletSelectorModal.tsx

- Update decentraland-gatsby to 5.71.0
- Use typescript 4.7.2
- Remove wallet connect v1 option
To test on staging use https://governance.decentraland.vote/

chore: update decentraland-gatsby 

---

src/clients/ErrorClient.ts
src/clients/Governance.ts
src/components/Debug/ErrorReporting.tsx
src/entities/Debug/routes.ts
src/services/ErrorService.ts

We are getting this in rollbar
- Errors coming from the frontend cannot be tagged with `{client: true}`, apparently it confuses rollbar. Changed it to `{frontend: true}`.
- Renamed `data` to `extraInfo`, to disencourage use of "data" tag since it is a reserved name - Grouped custom data in an `extraInfo` field.
Also, `DAO_ROLLBAR_TOKEN` constant is getting to the frontend when testing locally (though it should not get to the frontend in production environment). So reporting from the frontend using the ErrorClient is not working (it thinks it's in the backend and calls ErrorService, failing).
We should figure a different way to check if we are in the frontend+local from the ErrorClient.
This would work but it makes me sad:
```typescript
public static report(errorMsg: string, extraInfo?: …
```

fix: rename rollbar body vars

---

src/entities/Proposal/routes.ts
src/hooks/useProfile.ts

We are fetching profiles for invalid addresses
- Added check for valid address before trying to fetch profile
- Added backend validation for hiring address (if it's not valid, don't attempt to fetch profile and avoid creating a proposal)

chore: get profile address checks

---

src/components/User/Badges/BadgeDetail.tsx

fix: Badge description with URL

---

package-lock.json
package.json
src/back/routes/snapshot.ts
src/back/utils/validations.ts
src/clients/Governance.ts
src/clients/SnapshotApi.ts
src/clients/SnapshotGraphql.ts
src/entities/Votes/utils.ts
src/hooks/useProposalOutcome.ts
src/hooks/useVotingPowerBalanceList.ts
src/services/SnapshotService.ts

feat: use snapshot api key in all snapshot requests

---

src/clients/OtterspaceSubgraph.ts
src/components/User/Badges/BadgeDetail.css
src/components/User/Badges/BadgeDetail.tsx
src/entities/Badges/types.ts
src/entities/Transparency/utils.ts
src/intl/en.json

feat: add view on polygonscan link for minted badges

---

src/components/Modal/CalendarAlertModal.tsx
src/components/Proposal/ProposalSidebar.tsx
src/components/Proposal/View/CalendarAlertButton.css
src/components/Proposal/View/CalendarAlertButton.tsx
src/components/Proposal/View/SectionButton.css
src/components/Proposal/View/SidebarButton.tsx

feat: Calendar alert improvements

---

src/back/routes/badges.ts
src/back/routes/budget.ts
src/back/routes/coauthor.ts
src/back/routes/proposal.ts
src/back/routes/snapshot.ts
src/back/routes/user.ts
src/back/routes/votes.ts
src/back/services/vote.ts
src/back/utils/validations.test.ts
src/back/utils/validations.ts

chore: return validated values from validators

---

src/components/Proposal/View/Budget/CompetingGrants.tsx
src/components/Proposal/View/Budget/ProposalBudget.tsx
src/services/BudgetService.ts

fix: Show competing grants only on active ones

---

src/components/User/Badges/Badge.tsx
src/components/User/Badges/BadgeCard.css
src/components/User/Badges/BadgeWithTitle.css
src/components/User/Badges/BadgeWithTitle.tsx

**Description**
* Hover on icon now adds box-shadow to text container.
* Box shadow transition
Before
After

feat: update badge with title styles

---

src/components/Common/ProposalPreviewCard/ProposalPreviewCard.css
src/components/Profile/PriorityProposalsBox.tsx
src/entities/Bid/model.ts
src/entities/Bid/types.ts
src/entities/Proposal/model.ts
src/migrations/1688741539692_create-bids-table.ts
src/services/BidService.ts

- hide priority widget if there are no proposals after filtering by votes
- added loader when loading votes
- minor style tweaks
- filter tenders when bids are published

fix: priority widget fixes

---

src/components/Common/ActionBox.tsx
src/components/Profile/PriorityProposalsBox.tsx

Also added loader to collapsed widget

feat: save action box expanded state

---

src/back/models/Event.ts

If limited to 5, then
Ticker works fine

chore: limit activity ticker latest events to 50

---

src/back/routes/webhooks.ts
src/back/services/events.ts
src/entities/Proposal/jobs.ts
src/shared/types/events.ts

This PR requires a change in `ops-param-governance-alchemy-delegations-webhook-secret` for prd and zone
Events are now saved in order of tx confirmation.
Creation date is almost the same for events of the same transaction, with a ms difference according to the log index. There shouldn't be more than two events for each tx log (clear/set).
Also, there shouldn't be a problem if there are two tx confirmed in the same block (though it would be very unlikely). 
Worst case scenario, we have 2 `clear` events with same created_at and 2 `set` events with same created_at, but different tx hashes and for different addresses, so it would read:
```md
X set delegation to A
Z set delegation to B
X removed delegation from Y
Z removed delegation from W
```

fix: delegation events dates

---

src/back/routes/events.ts

Prod discourse webhook has been updated ✅

chore: remove old discourse comments endpoint

---

src/constants.ts

Once merged, cache key `core-units-badges` needs to be invalidated in prod (or wait 24hs)

chore: remove strategic unit badge cid from fetched badges

---

src/back/routes/proposal.ts
src/entities/Proposal/model.ts
src/entities/Proposal/types.ts
src/services/ProposalService.ts

Part of #1763 
Change single proposal endpoint to include basic project attributes on the response, so we can link to the project from the proposal page

chore: add basic project info to proposal data on proposals endpoint

---

src/back/models/Project.ts

fix: project query improvements
